services:
    akyos_mpdf.pdf:
        class: Akyos\MpdfBundle\Service\PDFService
        arguments: ["%kernel.cache_dir%"]
        public: true

    akyos_mpdf.mpdf:
        class: Akyos\MpdfBundle\Service\MpdfService
        public: true
